update plugin list

diff --git a/alpine-base/Dockerfile b/alpine-base/Dockerfile
--- a/alpine-base/Dockerfile
+++ b/alpine-base/Dockerfile
@@ -16,18 +16,33 @@ ARG GROUPNAME=jenkins
 ARG JENKINS_UC=https://updates.jenkins.io
 
 RUN apk add --no-cache --virtual=build-dependencies wget ca-certificates && \
-    apk add --no-cache openssh-client git curl unzip bash coreutils && \
+    apk add --no-cache openssh-client git curl unzip bash coreutils openssl && \
     addgroup -g ${GID} ${GROUPNAME} && \
     adduser -h ${JENKINS_HOME} -u ${UID} -G ${GROUPNAME} -G root -s /bin/bash -D ${USERNAME} && \
     mkdir -p /usr/share/jenkins/ref/init.groovy.d
 COPY init.groovy /usr/share/jenkins/ref/init.groovy.d/tcp-slave-agent-port.groovy
 
+RUN set -ex; \
+        apkArch="$(apk --print-arch)"; \
+        case "$apkArch" in \
+                x86_64) dockerArch=x86_64 ;; \
+                armhf) dockerArch=armel ;; \
+                *) echo >&2 "error: unknown Docker static binary arch $apkArch"; exit 1 ;; \
+        esac; \
+        curl -fSL "https://get.docker.com/builds/Linux/${dockerArch}/docker-17.03.1-ce.tgz" -o docker.tgz; \
+# /bin/sh doesn't support ${!...} :(
+        tar -xzvf docker.tgz; \
+        mv docker/* /usr/local/bin/; \
+        rmdir docker; \
+        rm docker.tgz; \
+        docker -v 
+
 #############################
 ### INSTALL GLIBC 2.25-r0 ###
 #############################
-RUN wget https://raw.githubusercontent.com/andyshinn/alpine-pkg-glibc/master/sgerrand.rsa.pub \
+RUN wget --progress=bar:force https://raw.githubusercontent.com/andyshinn/alpine-pkg-glibc/master/sgerrand.rsa.pub \
     -O /etc/apk/keys/sgerrand.rsa.pub && \
-    wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.25-r0/glibc-2.25-r0.apk \
+    wget --progress=bar:force https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.25-r0/glibc-2.25-r0.apk \
          https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.25-r0/glibc-bin-2.25-r0.apk \
          https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.25-r0/glibc-i18n-2.25-r0.apk && \
     apk add --no-cache glibc-2.25-r0.apk glibc-bin-2.25-r0.apk glibc-i18n-2.25-r0.apk && \
@@ -49,7 +64,7 @@ RUN apk add --no-cache tzdata && \
 ##########################
 ### DOWNLOAD JDK 8u131 ###
 ##########################
-RUN wget --header "Cookie: oraclelicense=accept-securebackup-cookie;" \
+RUN wget --progress=bar:force --header "Cookie: oraclelicense=accept-securebackup-cookie;" \
     "http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz" -O /tmp/jdk-${JDK_VER}-linux-x64.tar.gz && \
     tar -xvf /tmp/jdk-${JDK_VER}-linux-x64.tar.gz -C /tmp/ && \
     mkdir -p /usr/lib/jvm && mv /tmp/jdk1.8.0_131 ${JAVA_HOME} && \
@@ -87,7 +102,7 @@ RUN wget --header "Cookie: oraclelicense=accept-securebackup-cookie;" \
            "${JAVA_HOME}/jre/lib/jfr.jar" \
            "${JAVA_HOME}/jre/lib/jfr" \
            "${JAVA_HOME}/jre/lib/oblique-fonts" && \
-    wget --header "Cookie: oraclelicense=accept-securebackup-cookie;" \
+    wget --progress=bar:force --header "Cookie: oraclelicense=accept-securebackup-cookie;" \
         "http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip" -O /tmp/jce_policy-8.zip && \
     unzip -jo -d "${JAVA_HOME}/jre/lib/security" "/tmp/jce_policy-8.zip" && \
     apk del build-dependencies && \
@@ -104,7 +119,7 @@ COPY jenkins.sh install-plugins.sh plugins.txt plugin_loop.sh jenkins-support /u
 RUN curl -fsSL https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/2.46.2/jenkins-war-2.46.2.war -o /usr/share/jenkins/jenkins.war && \
     chown -R ${USERNAME}:${GROUPNAME} ${JENKINS_HOME} /usr/share/jenkins /usr/local/bin/install-plugins.sh /usr/local/bin/jenkins-support /usr/local/bin/jenkins.sh /usr/local/bin/plugin_loop.sh
 
-EXPOSE 8080 50000
+EXPOSE 22 8080 50000
 VOLUME /var/lib/jenkins
 USER ${USERNAME} 
 #RUN cd /usr/local/bin && ./plugin_loop.sh plugins.txt
